{% set name = "ibm-watson" %}
{% set version = "4.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b790842993375c11f9936314014314dfe067231315b425ab57656dd4f785788a


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ibm-cloud-sdk-core >=1.7.3,<1.8
    - python
    - python-dateutil >=2.5.3
    - requests >=2.0,<3.0
    - websocket-client >=0.48.0,<0.49.0

test:
  imports:
    - ibm_watson

about:
  home: https://github.com/watson-developer-cloud/python-sdk
  summary: Client library to use the IBM Watson Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
