{% set name = "ibm-watson" %}
{% set version = "5.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d52e57a0f018ce20aa280998dfbec1b51c0c0562e2ebfad491fd8f032f32c14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ibm-cloud-sdk-core >=3.3.6,==3.*
    - python >=3.6
    - python-dateutil >=2.5.3
    - requests >=2.0,<3.0
    - websocket-client ==1.1.0

test:
  imports:
    - ibm_watson
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/watson-developer-cloud/python-sdk
  summary: Client library to use the IBM Watson Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - BastianZim
