{% set name = "ibm-watson" %}
{% set version = "5.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b23f46002feb858375c3c599d21ce433967d68b9b87ac9fc4e3e10cccc293e54


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ibm-cloud-sdk-core >=1.5.1,<1.6
    - python
    - python-dateutil >=2.5.3
    - requests >=2.0,<3.0
    - websocket-client >=0.48.0,<0.49.0

test:
  imports:
    - ibm_watson

about:
  home: https://github.com/watson-developer-cloud/python-sdk
  summary: Client library to use the IBM Watson Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
